apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: code-server
  namespace: code-server
  labels:
    app: code-server
spec:
  serviceName: code-server
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-secret
                  key: PASSWORD
          volumeMounts:
            - name: workspace
              mountPath: /home/coder
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: code-server-data
