apiVersion: v1
kind: Namespace
metadata:
  name: sprint-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sprint-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: sprint-lab
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
