apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  labels:
    app: uptime-kuma
    student: jlgore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

