apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-required
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affinity-required
  template:
    metadata:
      labels:
        app: affinity-required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values: ["production"]
      containers:
      - name: nginx
        image: nginx:1.20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi