apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distributed-service
  template:
    metadata:
      labels:
        app: distributed-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - distributed-service
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi